"""create catalog.options table

Revision ID: a1b2c3d4e5f8
Revises: f6b7c8d9e0a1
Create Date: 2026-06-04 18:00:00.000000
"""
from typing import Sequence, Union

from alembic import op


revision: str = "a1b2c3d4e5f8"
down_revision: Union[str, Sequence[str], None] = "f6b7c8d9e0a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE IF NOT EXISTS catalog.options (
            id VARCHAR PRIMARY KEY,
            "12v_socket" BOOLEAN,
            "14_inch_wheels" BOOLEAN,
            "15_inch_wheels" BOOLEAN,
            "16_inch_wheels" BOOLEAN,
            "17_inch_wheels" BOOLEAN,
            "18_inch_wheels" BOOLEAN,
            "19_inch_wheels" BOOLEAN,
            "20_inch_wheels" BOOLEAN,
            "21_inch_wheels" BOOLEAN,
            "22_inch_wheels" BOOLEAN,
            "220v_socket" BOOLEAN,
            "23_inch_wheels" BOOLEAN,
            "24_inch_wheels" BOOLEAN,
            "360_camera" BOOLEAN,
            abs BOOLEAN,
            activ_suspension BOOLEAN,
            adaptive_light BOOLEAN,
            adj_pedals BOOLEAN,
            air_suspension BOOLEAN,
            airbag_curtain BOOLEAN,
            airbag_driver BOOLEAN,
            airbag_passenger BOOLEAN,
            airbag_rear_side BOOLEAN,
            airbag_side BOOLEAN,
            alarm BOOLEAN,
            alcantara BOOLEAN,
            android_auto BOOLEAN,
            apple_carplay BOOLEAN,
            aroma BOOLEAN,
            ashtray_and_cigarette_lighter BOOLEAN,
            asr BOOLEAN,
            athermal_glass BOOLEAN,
            audiopreparation BOOLEAN,
            audiosystem_cd BOOLEAN,
            audiosystem_tv BOOLEAN,
            auto_cruise BOOLEAN,
            auto_dimming_mirror BOOLEAN,
            auto_mirrors BOOLEAN,
            auto_park BOOLEAN,
            automatic_lighting_control BOOLEAN,
            aux BOOLEAN,
            bas BOOLEAN,
            black_roof BOOLEAN,
            blind_spot BOOLEAN,
            bluetooth BOOLEAN,
            body_kit BOOLEAN,
            body_mouldings BOOLEAN,
            cap_seats_rear BOOLEAN,
            central_airbag BOOLEAN,
            clean_air BOOLEAN,
            climate_control_1 BOOLEAN,
            climate_control_2 BOOLEAN,
            collision_prevention_assist BOOLEAN,
            combo_interior BOOLEAN,
            computer BOOLEAN,
            condition BOOLEAN,
            cooling_box BOOLEAN,
            cruise_control BOOLEAN,
            decorative_interior_lighting BOOLEAN,
            dha BOOLEAN,
            digital_mirror BOOLEAN,
            door_sill_panel BOOLEAN,
            drive_mode_sys BOOLEAN,
            driver_seat_electric BOOLEAN,
            driver_seat_memory BOOLEAN,
            driver_seat_support BOOLEAN,
            driver_seat_updown BOOLEAN,
            drl BOOLEAN,
            drowsy_driver_alert_system BOOLEAN,
            duo_body_color BOOLEAN,
            e_adjustment_wheel BOOLEAN,
            easy_trunk_opening BOOLEAN,
            eco_leather BOOLEAN,
            electro_mirrors BOOLEAN,
            electro_rear_seat BOOLEAN,
            electro_trunk BOOLEAN,
            electro_window_back BOOLEAN,
            electro_window_front BOOLEAN,
            electronic_gage_panel BOOLEAN,
            entertainment_system_for_rear_seat_passengers BOOLEAN,
            esp BOOLEAN,
            fabric_seats BOOLEAN,
            fake_complect BOOLEAN,
            fcw BOOLEAN,
            feedback_alarm BOOLEAN,
            folding_front_passenger_seat BOOLEAN,
            folding_tables_rear BOOLEAN,
            follow_me_home BOOLEAN,
            front_camera BOOLEAN,
            front_centre_armrest BOOLEAN,
            front_seat_support BOOLEAN,
            front_seats_heat BOOLEAN,
            front_seats_heat_vent BOOLEAN,
            glonass BOOLEAN,
            hatch BOOLEAN,
            hcc BOOLEAN,
            heated_wash_system BOOLEAN,
            high_beam_assist BOOLEAN,
            ignor_cme BOOLEAN,
            immo BOOLEAN,
            isofix BOOLEAN,
            isofix_front BOOLEAN,
            keyless_entry BOOLEAN,
            knee_airbag BOOLEAN,
            knee_airbag_pass BOOLEAN,
            laminated_safety_glass BOOLEAN,
            lane_keeping_assist BOOLEAN,
            laser_lights BOOLEAN,
            ldw BOOLEAN,
            leather BOOLEAN,
            leather_gear_stick BOOLEAN,
            led_lights BOOLEAN,
            lidar BOOLEAN,
            light_cleaner BOOLEAN,
            light_sensor BOOLEAN,
            lock BOOLEAN,
            massage_seats BOOLEAN,
            migration_flag BOOLEAN,
            mirrors_heat BOOLEAN,
            mirrors_memory BOOLEAN,
            multi_wheel BOOLEAN,
            multizone_climate_control BOOLEAN,
            music_super BOOLEAN,
            navigation BOOLEAN,
            night_vision BOOLEAN,
            paint_metallic BOOLEAN,
            panorama_roof BOOLEAN,
            park_assist_f BOOLEAN,
            park_assist_r BOOLEAN,
            passenger_seat_electric BOOLEAN,
            passenger_seat_updown BOOLEAN,
            pedestrian_detection BOOLEAN,
            power_child_locks_rear_doors BOOLEAN,
            power_latching_doors BOOLEAN,
            programmed_block_heater BOOLEAN,
            projection_display BOOLEAN,
            ptf BOOLEAN,
            rain_sensor BOOLEAN,
            rcta BOOLEAN,
            rear_armrest BOOLEAN,
            rear_camera BOOLEAN,
            rear_seat_heat_vent BOOLEAN,
            rear_seat_memory BOOLEAN,
            rear_seats_heat BOOLEAN,
            rec BOOLEAN,
            reduce_spare_wheel BOOLEAN,
            remote_car_services BOOLEAN,
            remote_engine_start BOOLEAN,
            roller_blind_for_rear_window BOOLEAN,
            roller_blinds_for_rear_side_windows BOOLEAN,
            roof_rails BOOLEAN,
            seat_memory BOOLEAN,
            seat_transformation BOOLEAN,
            servo BOOLEAN,
            side_camera BOOLEAN,
            spare_wheel BOOLEAN,
            sport_pedals BOOLEAN,
            sport_seats BOOLEAN,
            sport_suspension BOOLEAN,
            start_button BOOLEAN,
            start_stop_function BOOLEAN,
            steel_wheels BOOLEAN,
            steering_wheel_gear_shift_paddles BOOLEAN,
            third_rear_headrest BOOLEAN,
            third_row_seats BOOLEAN,
            tinted_glass BOOLEAN,
            tja BOOLEAN,
            traffic_sign_recognition BOOLEAN,
            tyre_pressure BOOLEAN,
            usb BOOLEAN,
            velvet_seats BOOLEAN,
            voice_recognition BOOLEAN,
            volume_sensor BOOLEAN,
            vsm BOOLEAN,
            wheel_configuration1 BOOLEAN,
            wheel_configuration2 BOOLEAN,
            wheel_heat BOOLEAN,
            wheel_leather BOOLEAN,
            wheel_memory BOOLEAN,
            wheel_power BOOLEAN,
            windcleaner_heat BOOLEAN,
            windscreen_heat BOOLEAN,
            wireless_charger BOOLEAN,
            xenon BOOLEAN,
            ya_auto BOOLEAN,
            updated_at TIMESTAMPTZ
        )
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS catalog.options")
